@startuml
'https://plantuml.com/class-diagram

package Leaosoft #DDDDDD {
    package UI {
        package Screens {
            interface IUIScreen {
                void Open();
                void Close();
            }
            
            UIScreen ..|> IUIScreen
        }
        
        ScreenService ..|> IScreenService
        ScreenService --> IUIScreen
    }
}

package Fantasy {
    package UI{
        Class Billboard
        Class ImageFiller
        
        package System {
            Class UISystem
        }
        
        package Screens {
            PlayConfirmationScreen ..|> UIScreen
            TitleScreen ..|> UIScreen
        }
        
        package Health {
            package Manager {
                Class HealthViewManager
            }
            
            HealthView --> Billboard
            HealthView --> ImageFiller
            
            HealthViewManager --> HealthView
        }
        
        UISystem --> HealthViewManager
    }
}



@enduml
